### ISSUE TITLE
外部容器大小变化，里面的echarts图不能同步改变

### ISSUE THREAD

**Issue by bengle** [liekkas/ng-echarts#8]
这个问题我已经用调用内部的refreshChart方法解决，但是当外部容器缩小到一定程度echart图的宽高就变成0了

**Comment by aspiders** [comment]
我也碰到这个问题，有解决办法？js里面是有resize方法，但具体怎么使用？

**Comment by aspiders** [comment]
@liekkas 能否指点迷津？

**Comment by ganshanshan** [comment]
可以贴出来代码看看吗？

**Comment by bengle** [comment]
就是如何解决，外部容器宽高改变后，里面的chart能够同步改变
我目前的做法是事件响应
// 响应大小变化
scope.$on('chartResize',()=>{
        refreshChart();
});

**Comment by perry2008084** [comment]
这个可以使用ng-style来实现，改变容器的大小
